### ISSUE TITLE
Filtering out attributes

### ISSUE THREAD

**Issue by ATriantafyllopoulos** [autrainer/hydra-filter-sweeper#7]
Currently struggling to use `expr` filters as they are documented in this repo (using the main branch of `autrainer`). I have the following `config`:
```
defaults:
  - _autrainer_
  - _self_
  - override hydra/sweeper: filter

results_dir: results
experiment_id: default
iterations: 1


hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +seed: 1
      +batch_size: 32
      +learning_rate: 0.001
      dataset: ToyTabular-C
      model: ToyFFNN,ASTModel-T
      optimizer: Adam
    filters:
      - type: expr
        expr: "model.id == 'ASTModel-T'"
```
and this fails with:

```
Traceback (most recent call last):
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/hydra_plugins/filter.py", line 138, in _filter_override
    should_filter = filter_cls().filter(
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/hydra_filter_sweeper/filters.py", line 84, in filter
    return Expr(expr).eval(config)
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/evalidate/__init__.py", line 122, in __init__
    v.visit(self.node)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/evalidate/__init__.py", line 79, in generic_visit
    ast.NodeVisitor.generic_visit(self, node)
  File "/usr/lib/python3.9/ast.py", line 417, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/evalidate/__init__.py", line 79, in generic_visit
    ast.NodeVisitor.generic_visit(self, node)
  File "/usr/lib/python3.9/ast.py", line 417, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/evalidate/__init__.py", line 81, in generic_visit
    raise ValidationException(
evalidate.ValidationException: Node type 'Attribute' is not allowed. (whitelist it manually)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 158, in sweep
    self.overrides = self.split_arguments(overrides, self.max_batch_size)
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/hydra_plugins/filter.py", line 70, in split_arguments
    return self._filter_overrides_list(overrides)
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/hydra_plugins/filter.py", line 92, in _filter_overrides_list
    if not self._filter_override(override, idx=idx):
  File "/home/trianand/envs/autrainer/lib/python3.9/site-packages/hydra_plugins/filter.py", line 145, in _filter_override
    raise ValueError(f"Filter {f} failed: {e}") from e
ValueError: Filter {'expr': "model.id == 'ASTModel-T'"} failed: Node type 'Attribute' is not allowed. (whitelist it manually)
```

I will update the issue as I understand more about the problem, but right now I am at "help please" :)

**Comment by ATriantafyllopoulos** [comment]
I found a potential solution, namely to allow `Attribute` in the "model" of `evalidate`, whatever the heck that is, and then add `id` to the model's possible attributes. This is a very "beat it with a hammer until it breaks solution" though, maybe you have a better one @ramppdev 

```python
from omegaconf import DictConfig
from evalidate import Expr, base_eval_model


config = DictConfig(
    {
        "foo": "bar",
        "nested_foo": {
            "foo": "nested_bar",
            "bar": "foo2"
        }
    }
)
# print(config)
# print(config.foo)
# exit()
expr = "foo == 'bar'"
print(Expr(expr).eval(config))


print(config.nested_foo.foo)
expr = "nested_foo.foo == 'nested_bar'"
# print(Expr(expr).eval(config))

my_model = base_eval_model.clone()
my_model.nodes.append("Attribute")
my_model.attributes.append("foo")
print(Expr(expr, model=my_model).eval(config))
```

**Comment by ramppdev** [comment]
This is not a bug, but rather a security feature of evalidate :D (see: https://github.com/yaroslaff/evalidate?tab=readme-ov-file#security).

Since our configuration is a `DictConfig` (which structure we do not know), we would have to manually allow all attributes that can be called on it:
(example taken from [here](https://github.com/yaroslaff/evalidate?tab=readme-ov-file#configure-validation))
```python
m = base_eval_model.clone()
m.nodes.extend(['Call', 'Attribute'])
m.attributes.append('startswith')

src = '"abcdef".startswith("abc")'
r = evalidate.Expr(src, model=m).eval()
```

However, since a `DictConfig` can essentially be treated as a dict, you could just do the following:
```yaml
...
hydra:
  sweeper:
    params:
      ...
    filters:
      - type: expr
        expr: model["id"] == "ASTModel-T"
```

Also, keep in mind when overriding the `filters` in the main configuration file, you also may want to include the [default filter checking for completed runs](https://autrainer.github.io/autrainer/usage/quickstart.html#quick-grid-filters)).

(btw `mode: MULTIRUN` is already set by autrainer)

**Comment by ATriantafyllopoulos** [comment]
Hmm, yes, accessing it as a `dict` works, maybe we should update the docs accordingly?

How about we also extend to allow `List` and/or `Tuple`, or do you see any trouble with that?

**Comment by ramppdev** [comment]
I dont have anything against allowing lists or tuples and basically assumed that the author has good reasons for their defaults.

Yeah good idea, the hydra filter sweeper docs should at least point the user towards the library. The intention was that more complex filters have to be implemented by a custom class-based filter so we are on the safe side and not just run arbitrary code.

**Comment by ATriantafyllopoulos** [comment]
So I would write my class in a local file and provide it as a `type: class`?

e.g.

```
# filter.py
class Foo:
    def filter(...):
```

**Comment by ramppdev** [comment]
Exactly, and then add the following filter:
```yaml
  - type: class
    target: filter.Foo
```
